apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
    name: multicontainer
    empresa: eso
  annotations:
    description: MicroServicio que provee información de servidor
    release: v1.0
spec:
  containers:
  - name: webstock
    image: rainscl/webstock:1.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000 
  - name: webzur
    image: rainscl/zchk8s:1.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  restartPolicy: Always