apiVersion: v1
kind: Pod
metadata:
  name: miweb
  labels:
    name: miweb
spec:
  containers:
  - name: miweb
    image: rainscl/webstock:1.1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
