apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    desc: "Servicio-para-website"
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
  selector:
    app: website
  
