apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    desc: "Servicio-para-website"
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  selector:
    app: nginx
  
